{% set name = "jupyterhub-kubespawner" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ac36cddc8229f3818e6ba08628d71ede991da253f49c3c1de3acba2fab98a44f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check"

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - escapism
    - jinja2
    - jupyterhub >=4.0.0
    - kubernetes_asyncio >=24.2.3
    - python-slugify
    - pyyaml
    - traitlets
    - urllib3

test:
  requires:
    - pip
  imports:
    - kubespawner
  commands:
    - pip check

about:
  home: https://github.com/jupyterhub/kubespawner
  dev_url: https://github.com/jupyterhub/kubespawner
  doc_url: https://jupyterhub-kubespawner.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Kubernetes spawner for JupyterHub
  description: |
    KubeSpawner enables JupyterHub to start and manage single-user notebook
    servers on a Kubernetes cluster.

extra:
  recipe-maintainers:
    - consideratio
    - dhirschfeld
    - manics
